# -*- coding: utf-8 -*-
"""Pandas_Practical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c39cdvItW1u_949Fv8c6OlJgAeRX3xjc

---
# Section 1 — The only two objects

Everything in Pandas is a **Series** (one column) or a **DataFrame** (a whole table).
Learn the pair and the rest is method names.
"""

import pandas as pd            # load the Pandas library and call it "pd" from now on (everyone does this)
import numpy as np             # load NumPy too - Pandas is built on top of it and we will use np.where later

print("pandas version:", pd.__version__)   # print which version Colab gave you
print("numpy version :", np.__version__)   # and which NumPy - both are already installed, nothing to pip install

# ---- A SERIES is one column of data ----

s = pd.Series([78, 55, 91, 42])   # pd.Series( ) takes a list and turns it into a labelled column

print(s)                          # printing shows two columns: the INDEX on the left, the values on the right

print(s.values)                   # .values gives you the raw array underneath - just values, no labels
print(type(s.values).__name__)    # "ndarray" for a number column - it really IS a NumPy array
                                  # (a TEXT column may say StringArray on newer Pandas - same idea, different box)

print(list(s.index))              # .index gives the labels; list( ) makes them print tidily

# The index does not have to be 0,1,2. You can label rows with anything.

named = pd.Series([78, 55, 91],                      # the values
                  index=["Aisha", "Ben", "Carla"])   # index= gives each value a name instead of a number

print(named)                      # now the left-hand column shows names
print()                           # a blank line to separate the outputs

print(named["Ben"])               # look a value up BY ITS LABEL - this is what a plain array cannot do
print(named.mean())               # every NumPy aggregation still works: mean, sum, min, max, std

"""### ⭐ YOUR TURN 1

Make a Series called `temps` holding `18, 22, 31, 27`, with the index `"Mon", "Tue", "Wed", "Thu"`.
Then print Wednesday's temperature and the average of all four.
"""

# YOUR TURN 1 - write your code here

temps = pd.Series([18, 22, 31, 27 ], index=["Mon", "Tue", "Wed", "Thu" ])   # TODO 1: fill in the values and the index
print(temps)                                # TODO 2: look at the whole thing
print(temps["Wed"])                         # TODO 3: one value, by its label
print(temps.mean())                         # TODO 4: the average

"""---
# Section 2 — Loading data

Two ways in: build it from a dictionary, or read a file.
"""

# ---- WAY 1: from a dictionary ----
# The KEYS become the column names. Each LIST becomes one column.

students = pd.DataFrame({                                                        # pd.DataFrame( ) takes a dictionary
    "name":    ["Aisha", "Ben", "Carla", "Dev", "Eli", "Farah", "Gita", "Hari"], # eight students
    "branch":  ["CSE", "ECE", "CSE", "MECH", "ECE", "CSE", "MECH", "ECE"],       # which branch each one is in
    "year":    [2, 2, 3, 2, 3, 3, 2, 3],                                         # which year of the course
    "maths":   [78, 55, 91, 42, 67, 83, 71, 60],                                 # marks out of 100
    "physics": [65, 71, 88, 38, 74, 97, 58, 82],                                 # more marks
    "english": [82, 60, 79, 55, 71, 68, 90, 64],                                 # more marks
})                                                                               # the } closes the dict, the ) the call

print(students)      # printing a DataFrame lays it out as a table, with the index down the left

# ---- WAY 2: from a CSV file ----
# First we WRITE one, so there is nothing for you to upload.

students.to_csv("students.csv", index=False)   # .to_csv( ) saves the table as a text file
                                               # index=False stops it writing the 0,1,2 column into the file

df = pd.read_csv("students.csv")               # read it straight back in - THIS is the line you will type most often

print(df.head())                               # .head( ) shows the first five rows so you can eyeball it

print(df.head(3))     # 1. THE FIRST ROWS - does this look like what you expected?
                      #    head( ) gives five by default; head(3) gives three

print(df.shape)       # 2. THE SIZE - a tuple of (rows, columns). Is it as big as you thought?
                      #    Same .shape attribute you used in NumPy yesterday

print(df.columns)     # 3. THE COLUMN NAMES - exactly how are they spelled?
                      #    Nearly every Pandas error is a name typed slightly wrong

print(list(df.columns))   # list( ) prints them more readably than the raw Index object

df.info()             # 4. TYPES AND GAPS - note there is no print( ), info( ) prints by itself
                      #    Read the "Non-Null Count" column: 8 non-null out of 8 rows means nothing is missing
                      #    For TEXT columns the Dtype says "object" on Pandas 2 and "str" on Pandas 3.
                      #    They are not identical under the hood, but for today they mean the same: "this is text"

print(df.describe())  # 5. THE NUMBERS - count, mean, std, min, quartiles and max
                      #    It quietly SKIPS the text columns, because you cannot average a name

"""---
# Section 3 — Selecting columns

One bracket or two. This catches everybody once.
"""

maths_col = df["maths"]              # ONE bracket, one column name -> you get a SERIES back

print(maths_col)                     # note the "Name: maths" line at the bottom - that only appears on a Series
print(type(maths_col).__name__)      # "Series" - .__name__ just prints the type's name tidily

two_cols = df[["name", "maths"]]     # TWO brackets. The inner [ ] is a LIST of names; the outer [ ] is the lookup.

print(two_cols)                      # you get a DATAFRAME back - it prints as a table
print(type(two_cols).__name__)       # "DataFrame"

one_col_frame = df[["maths"]]        # TWO brackets with only ONE name inside

print(type(one_col_frame).__name__)  # still "DataFrame" - the brackets decide the type, not how many names

print(df["maths"].mean())            # works - a Series has .mean( )
print(df["maths"].max())             # so does .max( )
print(df["branch"].unique().tolist())  # .unique( ) lists the distinct values; .tolist( ) makes it a plain Python list
print(df["branch"].nunique())        # .nunique( ) just counts how many distinct values there are

"""### ⭐ YOUR TURN 2

1. Print the `physics` column on its own.
2. Print a two-column table of `name` and `physics`.
3. Print the average physics mark.
"""

# YOUR TURN 2 - write your code here

print(df["physics" ])            # TODO 1: one bracket, one name
print(df[[ "name", "physics" ]])        # TODO 2: two brackets, two names in a list
print(df["physics"].mean())     # TODO 3: get the column first, then ask it for its mean

"""---
# Section 4 — `.loc` and `.iloc`

Two ways to pick rows. This is the part people get wrong, so we will be slow about it.

- **`.iloc`** — by **position**. The `i` is for integer. Exactly like NumPy.
- **`.loc`** — by **label**. The row's index label, and the column's name.
"""

# ---- .iloc : by POSITION ----

print(df.iloc[0])         # row at position 0 - the FIRST row, returned as a Series
                          # the column names run down the left, because a single row turned sideways is a Series

print(df.iloc[0:3])       # rows at positions 0, 1, 2 - the stop is EXCLUDED, exactly like list slicing

print(df.iloc[0, 3])      # [row position, column position] -> row 0, column 3
                          # counting the columns: 0=name, 1=branch, 2=year, 3=maths -> so this is 78

print(df.iloc[-1])        # -1 counts from the end, so this is the LAST row

print(df.iloc[0:3, 0:2])  # a rectangle: rows 0-2 and columns 0-1
                          # both stops are excluded, so you get 3 rows and 2 columns

"""### `.loc` — by label"""

print(df.loc[0, "maths"])          # [row LABEL, column NAME] - much easier to read than iloc[0, 3]
                                   # you do not have to count columns, you just say what you want

print(df.loc[0:2, ["name", "maths"]])   # rows labelled 0 to 2, and a LIST of column names

print("iloc[0:3] gives", len(df.iloc[0:3]), "rows")   # len( ) counts the rows - 3, stop excluded
print("loc[0:2]  gives", len(df.loc[0:2]), "rows")    # also 3 - but note we asked for 0 to 2, not 0 to 3

sorted_df = df.sort_values("maths", ascending=False)   # sort by maths, biggest first
                                                       # ascending=False means high-to-low
                                                       # (sorting gets its own section later - we only
                                                       #  need it here to shuffle the index)

print(sorted_df[["name", "maths"]])   # look at the INDEX on the left - it is jumbled, not 0,1,2,3
                                      # Carla was row 2 in the original and she still carries the label 2

print("iloc[0] - the TOP row:")           # a label so the output is readable
print(sorted_df.iloc[0]["name"])          # position 0 = whoever is now at the top = Carla

print("loc[0] - the row LABELLED 0:")     # another label
print(sorted_df.loc[0]["name"])           # label 0 = Aisha, who is now sitting in the middle somewhere

"""---
# Section 5 — Filtering rows

Good news: this is **exactly** yesterday's boolean masking. Same symbols, same brackets, same rules.
"""

mask = df["maths"] > 70      # a comparison on a column gives one True/False PER ROW, not a single answer

print(mask)                  # a Series of True and False, the same length as the table
print(mask.dtype)            # bool - it is a real Series, just holding True/False instead of numbers

print(df[mask])              # put the True/False Series inside the brackets to keep only the True rows

print()                      # blank line
print(df[df["maths"] > 70])  # the same thing written in one line - this is the version you will use

# ---- two conditions ----

print(df[(df["maths"] > 70) & (df["branch"] == "CSE")])   # & means BOTH must be true
                                                          # note the brackets around EACH condition - compulsory

print(df[(df["maths"] > 85) | (df["physics"] > 85)])      # | means EITHER one is enough

print(df[~(df["branch"] == "CSE")])   # ~ flips every True to False, so this is "everyone NOT in CSE"

print(df[df["branch"].isin(["CSE", "MECH"])])   # .isin( ) checks against a LIST of allowed values
                                                # this saves writing  (b == "CSE") | (b == "MECH")

print("how many scored over 70:", (df["maths"] > 70).sum())   # True counts as 1, False as 0, so .sum( ) COUNTS
print("did anyone score over 90:", (df["maths"] > 90).any())  # .any( ) is True if at least one is True
print("did everyone pass 40:    ", (df["maths"] > 40).all())  # .all( ) is True only if every single one is True

"""### ⭐ YOUR TURN 3

1. Everyone in year 3.
2. Everyone in ECE who scored above 60 in physics.
3. How many students are in CSE?
"""

print(df[df["year" ] == 3])                          # TODO 1: one condition
print(df[(df["branch"] == "ECE") & (df["physics"] > 60)])     # TODO 2: two conditions, brackets round each
print((df["branch"] == "CSE").sum())                  # TODO 3: build the mask, then .sum( ) it

"""---
# Section 6 — The copy trap ⚠️


"""

cse = df[df["branch"] == "CSE"]    # filter down to the CSE students - this builds a NEW little table

cse["maths"] = 100                 # set every maths mark in THAT table to 100
                                   # (older Pandas prints a SettingWithCopyWarning here; newer versions say nothing)

print("the filtered table:")       # a label
print(cse[["name", "maths"]])      # inside cse, the marks really are 100

print("the original table:")            # a label
print(df[["name", "maths"]].head(3))    # ...but the original is completely untouched

print("Aisha's maths in df is still:", df.loc[0, "maths"])   # 78, not 100

# ---- FIX 1: you genuinely want a separate table - say so with .copy( ) ----

cse_copy = df[df["branch"] == "CSE"].copy()   # .copy( ) makes it explicit: this is mine, it is separate

cse_copy["maths"] = 100                       # now nobody is confused about what you meant

print(cse_copy[["name", "maths"]])            # the copy has 100s
print("original untouched:", df.loc[0, "maths"])   # and df is still 78, which is what we wanted

# ---- FIX 2: you want to change the ORIGINAL - do it in one .loc ----

df2 = df.copy()                                          # work on a copy of df so the rest of the notebook is unaffected

df2.loc[df2["branch"] == "CSE", "maths"] = 100           # .loc[which rows, which column] = new value
                                                         # one step: pick the rows AND the column AND assign, together

print(df2[["name", "branch", "maths"]])                  # the CSE students really did change this time

"""---
# Section 7 — New columns and missing data
"""

df["total"] = df["maths"] + df["physics"] + df["english"]   # assign to a name that does not exist yet and it APPEARS
                                                            # the addition is element-wise: row 0 + row 0, row 1 + row 1

df["average"] = (df["total"] / 3).round(1)                  # divide the whole column by 3, then .round(1) to 1 decimal

df["result"] = np.where(df["average"] >= 60, "pass", "fail")   # yesterday's np.where: condition, if-true, if-false
                                                               # it takes a Pandas Series just as happily as an array

print(df[["name", "total", "average", "result"]])           # show just the four columns we care about

df_dropped = df.drop(columns=["english"])   # .drop( ) removes columns; it returns a NEW table

print(list(df_dropped.columns))             # english is gone from the new one
print(list(df.columns))                     # ...but still present in the original, because drop did not change it

df_renamed = df.rename(columns={"maths": "Maths"})   # rename takes a dictionary: {old name: new name}

print(list(df_renamed.columns))                      # "maths" is now "Maths" - capital M

"""### Missing data — `NaN`

Every real dataset has holes. Pandas marks them **NaN** ("not a number") and you have to decide
what to do about each one.
"""

messy = pd.DataFrame({                              # a small table with deliberate gaps
    "name": ["Aisha", "Ben", "Carla", "Dev"],       # four names, none missing
    "maths": [78, np.nan, 91, 42],                  # np.nan is the missing-value marker - Ben's mark is absent
    "physics": [65, 71, np.nan, 38],                # Carla's physics mark is absent
})                                                  # the } closes the dictionary, the ) closes DataFrame( )

print(messy)                                        # the gaps print as NaN

print(messy.isna())          # .isna( ) gives a True/False table - True wherever a value is missing

print(messy.isna().sum())    # .sum( ) on that True/False table COUNTS the Trues, one count per column
                             # this two-word line is how you check any new file for gaps

print(messy["maths"].mean())   # mean( ) SKIPS the NaN automatically - it does not crash, and it does
                               # not treat the gap as a zero: (78 + 91 + 42) / 3 = 70.33, NOT divided by 4
                               # (careful: sum( ) also skips NaN, but for a SUM that is the same answer
                               #  you would get by treating it as zero - the difference only shows in mean)

print(messy.dropna())        # .dropna( ) deletes every ROW that has any gap at all
                             # safe, but here it throws away half your data to fix two cells

print(messy.fillna(0))       # .fillna(0) puts 0 in every gap
                             # fast - but a 0 mark is a LIE. It says Ben scored nothing.

filled = messy.copy()                                            # work on a copy so `messy` stays messy for later

filled["maths"] = filled["maths"].fillna(filled["maths"].mean()) # fill the gaps in maths with the average OF maths
                                                                 # read it inside-out: work out the mean, then fill with it

print(filled)                                                    # Ben now has 70.333333, the average of the other three

"""---
# Section 8 — Sorting, counting, grouping
"""

print(df.sort_values("total", ascending=False)[["name", "total"]])   # sort by total, biggest first
                                                                     # then [[ ]] picks the two columns to display

print(df.sort_values(["branch", "total"],          # sort by TWO columns: branch first, then total within each branch
                     ascending=[True, False]       # branch A-Z (True), but total high-to-low (False)
                     )[["name", "branch", "total"]])   # show three columns

print(df["branch"].value_counts())   # how many students in each branch - one word, and it sorts biggest first

print(df.groupby("branch")["maths"].mean().round(2))   # SPLIT by branch, APPLY mean to the maths column, COMBINE
                                                       # .round(2) just trims the decimals for readability

# .agg( ) takes a LIST of what you want, and gives you one column for each:
# count = how many are in the group, mean = the average, max = the biggest
print(df.groupby("branch")["total"].agg(["count", "mean", "max"]).round(2))   # three answers per branch

print(df.groupby(["branch", "year"])["total"].mean().round(1))   # group by TWO columns
                                                                 # you get one row per combination that exists

"""### ⭐ YOUR TURN 4

1. The average `physics` mark per branch.
2. The number of students in each `year`.
3. The highest `total` in each branch.
"""

# YOUR TURN 4 - write your code here

print(df.groupby('branch')['physics'].mean().round(2))   # TODO 1: group by branch, take physics, take the mean
print(df['year'].value_counts())               # TODO 2: value_counts on the year column
print(df.groupby('branch')['total'].max())             # TODO 3: same shape as TODO 1, but max instead of mean

"""---
# Section 9 — Joining tables, and saving your work
"""

branch_info = pd.DataFrame({                          # a second, small table
    "branch": ["CSE", "ECE", "MECH"],                 # the SHARED column - it must be spelled the same in both
    "hod": ["Dr Rao", "Dr Iyer", "Dr Shah"],          # the extra information we want to bring across
})                                                    # } closes the dictionary, ) closes the DataFrame( ) call

print(branch_info)                                    # three rows, two columns

merged = df.merge(branch_info, on="branch")   # .merge( ) glues the two tables together on the shared column
                                              # on="branch" says which column to match rows up by

print(merged[["name", "branch", "hod"]])      # every student now carries their head of department

print("df shape    :", df.shape)          # (8, 9) - the original 6 columns plus total, average and result
print("merged shape:", merged.shape)      # (8, 10) - one extra column (hod), and the SAME number of rows

merged.to_csv("class_report.csv", index=False)   # save the finished table as a file
                                                 # index=False stops the 0,1,2 labels being written as a column

check = pd.read_csv("class_report.csv")          # read it straight back to prove it worked
print(check.head(3))                             # the first three rows of the saved file

"""---
# ★ Mini project — the class report

Everything from today, on one table. Work through it cell by cell.
"""

# ---- Start fresh from the file, the way a real analysis begins ----

report = pd.read_csv("students.csv")   # read the CSV we wrote back in Section 2

print(report.shape)                    # (8, 6) - eight students, six columns
print(list(report.columns))            # check the names before doing anything else

# ---- 1. Build the derived columns ----

report["total"] = report["maths"] + report["physics"] + report["english"]   # add the three subject columns together
report["average"] = (report["total"] / 3).round(1)                          # divide by 3 and round to 1 decimal

report["grade"] = np.where(report["average"] >= 80, "A",                    # 80 and above -> "A"
                  np.where(report["average"] >= 65, "B", "C"))              # otherwise 65+ -> "B", else "C"
                                                                            # this is an np.where INSIDE another one

print(report[["name", "total", "average", "grade"]])                        # show the result

# ---- 2. Who is top of the class? ----

ranked = report.sort_values("total", ascending=False)   # sort high to low

print(ranked[["name", "branch", "total"]].head(3))      # .head(3) gives the top three

print()                                                 # blank line
print("Top student:", ranked.iloc[0]["name"])           # iloc[0] is the top ROW after sorting; ["name"] pulls one value

# ---- 3. Per-branch summary ----

by_branch = report.groupby("branch")["total"].agg(["count", "mean", "max"]).round(1)   # three numbers per branch

print(by_branch)                                        # count, mean and max for CSE, ECE and MECH

# ---- 4. Per-subject averages ----

subjects = ["maths", "physics", "english"]              # a list of the three subject column names

print(report[subjects].mean().round(2))                 # pick those three columns, then .mean( ) averages EACH column
                                                        # you get one number per subject

# ---- 5. Who is at risk? (any single subject below 50) ----

at_risk = report[(report["maths"] < 50) |               # low in maths...
                 (report["physics"] < 50) |             # ...OR low in physics...
                 (report["english"] < 50)]              # ...OR low in english

print(at_risk[["name", "maths", "physics", "english"]]) # show their three marks so you can see why

# ---- 6. Grade distribution ----

print(report["grade"].value_counts())                   # how many A, B and C grades were awarded

# ---- 7. Bring in the head of department ----

final = report.merge(branch_info, on="branch")          # glue on the hod column from the small table

print(final[["name", "branch", "hod", "grade"]])        # a tidy four-column view

# ---- 8. The printed report ----

print("=" * 48)                                                   # "=" * 48 repeats the = sign to make a line
print("CLASS REPORT")                                             # a heading
print("=" * 48)                                                   # another line

ranked_final = final.sort_values("total", ascending=False)        # highest total first

for place in range(len(ranked_final)):                            # one turn per student, in ranking order
    row = ranked_final.iloc[place]                                # iloc[place] gives that whole row as a Series
    name = str(row["name"]).ljust(8)                              # pull the name out; .ljust(8) pads it so columns line up
    branch = str(row["branch"]).ljust(6)                          # same for the branch
    print(place + 1, name, branch, "total", row["total"], " grade", row["grade"])   # place + 1 because humans count from 1

print("-" * 48)                                                   # a divider
print("Class average :", round(float(report["average"].mean()), 2))   # the average of the averages
print("Highest total :", report["total"].max())                       # the single best total
print("Lowest total  :", report["total"].min())                       # and the worst
print("Grade A count :", (report["grade"] == "A").sum())              # count the Trues
print("=" * 48)                                                       # closing line

# ---- 9. Save it ----

final.to_csv("final_report.csv", index=False)      # write the finished table to a file

print("saved. shape:", final.shape)                # confirm what we saved
print(pd.read_csv("final_report.csv").head(2))     # read the first two rows back as proof

"""---
### ⭐ FINAL CHALLENGE

Add cells below and answer these, using `final`:

1. Which **branch** has the highest average total?
   *(Hint: `groupby(...)["total"].mean()` gives you a Series whose INDEX is the branch names. A Series
   has a method `.idxmax()` — "index of the max" — which hands back the label of the biggest value
   rather than the value itself. So the whole answer is one chained line.)*
2. Print every student whose `average` is above the class average.
   *(Hint: work out `report["average"].mean()` first, then use it in a filter.)*
3. Add a column `rank` numbering the students 1 to 8 by total, best first.
   *(Hint: sort `final` first and save the result, then assign `range(1, len(final) + 1)` to a new
   column on the sorted table.)*
4. Save a CSV containing only the year-3 students, sorted by total.
"""

# FINAL CHALLENGE - your code here

# 1. Which branch has the highest average total?
print("1. Branch with the highest average total:")
highest_avg_total_branch = final.groupby('branch')['total'].mean().idxmax()
print(highest_avg_total_branch)
print()

# 2. Print every student whose average is above the class average.
print("2. Students with average above class average:")
class_average = report['average'].mean()
students_above_avg = final[final['average'] > class_average]
print(students_above_avg[['name', 'branch', 'average']])
print()

# 3. Add a column rank numbering the students 1 to 8 by total, best first.
print("3. Students with rank column:")
final_ranked = final.sort_values('total', ascending=False).copy()
final_ranked['rank'] = range(1, len(final_ranked) + 1)
print(final_ranked[['name', 'total', 'rank']])
print()

# 4. Save a CSV containing only the year-3 students, sorted by total.
print("4. Saving year-3 students to CSV:")
year_3_students = final[final['year'] == 3].sort_values('total', ascending=False)
year_3_students.to_csv('year_3_students_report.csv', index=False)
print("  'year_3_students_report.csv' created with the following data (first 5 rows):")
print(year_3_students.head())