# -*- coding: utf-8 -*-
"""Plotting_Practical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SW8jbiVEsR361Uadb-vWuI9D7nWZI1-e

---
# Section 1 — Why plot at all?

You can already calculate a mean, a standard deviation and a correlation. So why draw pictures?

Here is the answer, and it is 50 years old.
"""

import matplotlib.pyplot as plt   # the plotting library - ALWAYS imported as plt, by everybody
import seaborn as sns             # the friendlier layer on top of it - ALWAYS imported as sns
import pandas as pd               # yesterday's library, for the DataFrames
import numpy as np                # for a bit of random data later on

print("matplotlib:", plt.matplotlib.__version__)   # print the versions so you know what you have
print("seaborn   :", sns.__version__)              # Colab already has both - nothing to install

# Four small datasets, invented in 1973 by a statistician called Francis Anscombe.

anscombe = pd.DataFrame({                                    # build them as one tidy DataFrame
    "set": ["I"] * 11 + ["II"] * 11 + ["III"] * 11 + ["IV"] * 11,   # a label saying which set each row belongs to
                                                                    # ["I"] * 11 repeats the string eleven times
    "x": [10, 8, 13, 9, 11, 14, 6, 4, 12, 7, 5] * 3              # sets I, II and III share the same x values
         + [8, 8, 8, 8, 8, 8, 8, 19, 8, 8, 8],                   # set IV has its own x values
    "y": [8.04, 6.95, 7.58, 8.81, 8.33, 9.96, 7.24, 4.26, 10.84, 4.82, 5.68,   # set I
          9.14, 8.14, 8.74, 8.77, 9.26, 8.10, 6.13, 3.10, 9.13, 7.26, 4.74,    # set II
          7.46, 6.77, 12.74, 7.11, 7.81, 8.84, 6.08, 5.39, 8.15, 6.42, 5.73,   # set III
          6.58, 5.76, 7.71, 8.84, 8.47, 7.04, 5.25, 12.50, 5.56, 7.91, 6.89],  # set IV
})                                                           # } closes the dictionary, ) closes DataFrame( )

print(anscombe.head())      # a quick look at the first five rows

# Now work out the statistics for each of the four sets.

for name in ["I", "II", "III", "IV"]:                       # one turn of the loop per set
    sub = anscombe[anscombe["set"] == name]                 # filter down to just that set (yesterday's masking)
    print(name,                                             # which set we are looking at
          "mean x:", round(sub["x"].mean(), 2),             # the average of the x column, to 2 decimals
          " mean y:", round(sub["y"].mean(), 2),            # the average of the y column
          " std y:", round(sub["y"].std(), 2),              # how spread out the y values are
          " corr:", round(sub["x"].corr(sub["y"]), 3))      # how strongly x and y move together

fig, axes = plt.subplots(1, 4, figsize=(14, 3))     # make ONE picture with 1 row and 4 columns of charts
                                                    # figsize is (width, height) in inches
                                                    # "axes" is the list of the four panels

for i in range(4):                                  # loop 0, 1, 2, 3 - one turn per panel
    name = ["I", "II", "III", "IV"][i]              # pick the set name for this turn
    sub = anscombe[anscombe["set"] == name]         # filter to just that set
    axes[i].scatter(sub["x"], sub["y"], color="crimson")   # draw dots into panel number i
    axes[i].set_title("Set " + name)                # give that panel a title
    axes[i].set_xlim(2, 20)                         # force the same x range on all four, so they are comparable
    axes[i].set_ylim(2, 14)                         # and the same y range

plt.tight_layout()                                  # stop the titles and labels overlapping
plt.show()                                          # draw it

"""---
# Section 2 — Your first chart

Two lines. Everything else today is decoration on top of them.
"""

plt.plot([1, 2, 3, 4], [10, 25, 18, 40])   # plt.plot(x values, y values) - draws a line joining the points
                                           # the FIRST list is across, the SECOND is up
                                           # they must be the same length - four x's and four y's

plt.show()                                 # "draw it now" - always the last line of a chart cell

# The same data with the stray text line, so you can see what we are avoiding.

plt.plot([1, 2, 3, 4], [10, 25, 18, 40])   # draw the chart but do NOT call show( )
                                           # look above the chart - there is a line of [<matplotlib...>] text

"""### The three labels

A chart without labels is not a chart. It is a decoration. **Three lines, every time, no exceptions.**
"""

plt.plot([1, 2, 3, 4], [10, 25, 18, 40],   # the same data as before
         color="crimson",                  # colour of the line - names like "crimson", "steelblue", "seagreen" all work
         marker="o",                       # put a dot at each actual data point
         linewidth=2)                      # how thick the line is

plt.title("Weekly sign-ups")               # 1. what am I looking at?
plt.xlabel("Week")                         # 2. what is along the bottom?
plt.ylabel("Sign-ups")                     # 3. what is up the side?
plt.grid(True, alpha=0.3)                  # faint gridlines; alpha is see-through-ness, 0 = invisible, 1 = solid

plt.show()                                 # draw it

"""### ⭐ YOUR TURN 1

Draw a line chart of these five temperatures: `18, 22, 31, 27, 15` against the days `1, 2, 3, 4, 5`.
Give it a title, both axis labels, and a colour of your choosing.
"""

days = [1, 2, 3, 4, 5]              # the x values, ready for you
temps = [18, 22, 31, 27, 15]        # the y values

plt.plot(days, temps, color="red")  # TODO 1: remove the # and pick a colour
plt.title("Temperature vs Days")                    # TODO 2: what is this chart about?
plt.xlabel("Days")                   # TODO 3: what is along the bottom?
plt.ylabel("Temperature")                   # TODO 4: what is up the side?
plt.show()                        # TODO 5: draw it

"""---
# Section 3 — Line and bar charts

First, the data we will use for the rest of the notebook. It is the same table as yesterday.
"""

students = pd.DataFrame({                                                        # the same eight students as Day 7
    "name":    ["Aisha", "Ben", "Carla", "Dev", "Eli", "Farah", "Gita", "Hari"], # who they are
    "branch":  ["CSE", "ECE", "CSE", "MECH", "ECE", "CSE", "MECH", "ECE"],       # which branch
    "year":    [2, 2, 3, 2, 3, 3, 2, 3],                                         # which year
    "maths":   [78, 55, 91, 42, 67, 83, 71, 60],                                 # marks out of 100
    "physics": [65, 71, 88, 38, 74, 97, 58, 82],                                 # more marks
    "english": [82, 60, 79, 55, 71, 68, 90, 64],                                 # more marks
})                                                                               # } closes the dict, ) the call

students["total"] = students["maths"] + students["physics"] + students["english"]   # add the three subjects up
students["average"] = (students["total"] / 3).round(1)                              # and the average, to 1 decimal

print(students)      # look at the table before plotting anything from it

weeks = [1, 2, 3, 4, 5, 6]              # six weeks - these have a natural order
signups = [10, 25, 18, 40, 38, 52]      # how many people signed up each week

plt.figure(figsize=(7, 4))              # make the picture 7 inches wide and 4 tall - do this BEFORE plotting
plt.plot(weeks, signups, color="crimson", marker="o", linewidth=2)   # the line itself
plt.title("Weekly sign-ups")            # the title
plt.xlabel("Week")                      # bottom label
plt.ylabel("Sign-ups")                  # side label
plt.grid(True, alpha=0.3)               # faint gridlines
plt.show()                              # draw it

plt.figure(figsize=(7, 4))                                        # set the picture size first
plt.bar(students["name"], students["maths"], color="steelblue")   # plt.bar(labels, heights)
                                                                  # one bar per name, height = the maths mark
plt.title("Maths mark by student")                                # title
plt.xlabel("Student")                                             # bottom label
plt.ylabel("Maths mark")                                          # side label
plt.show()                                                        # draw it

# Sorting first makes a bar chart much easier to read.

ordered = students.sort_values("total")            # sort the table by total, smallest first

plt.figure(figsize=(7, 4))                         # set the size
plt.barh(ordered["name"], ordered["total"],        # barh = HORIZONTAL bars; good when names are long
         color="seagreen")                         # the colour
plt.title("Total marks, lowest to highest")        # title
plt.xlabel("Total")                                # for barh, the NUMBER is now along the bottom
plt.show()                                         # draw it

"""### ⭐ YOUR TURN 2

Draw a bar chart of each student's **physics** mark. Sort the table by physics first, and give the
chart all three labels.
"""

by_physics = students.sort_values("physics")               # TODO 1: which column do you sort by?
plt.figure(figsize=(7, 4))                           # TODO 2: set the size
plt.bar(by_physics["name"], by_physics["physics"])            # TODO 3: names for the labels, physics for the heights
plt.title("Physics marks by student")                                       # TODO 4
plt.xlabel("Student")                                      # TODO 5
plt.ylabel("Physics mark")                                      # TODO 6
plt.show()                                           # TODO 7

"""---
# Section 4 — Histograms

A histogram answers a completely different question from a bar chart:
**"what SHAPE is this spread of numbers?"**
"""

rng = np.random.default_rng(42)          # a random number generator with a fixed seed, so everyone matches
exam = rng.normal(65, 12, 200).round()   # 200 fake exam marks: average 65, spread 12, rounded to whole numbers

print("how many marks:", len(exam))      # 200
print("first ten     :", exam[:10])      # a peek at the start
print("average       :", round(exam.mean(), 1))   # roughly 65, as we asked for

plt.figure(figsize=(7, 4))                      # set the picture size
plt.hist(exam,                                  # the ONE column of numbers we want the shape of
         bins=10,                               # chop the range into 10 buckets
         color="mediumpurple",                  # bar colour
         edgecolor="white")                     # a white line between bars, so you can see where each one ends
plt.title("Exam marks, 200 students")           # title
plt.xlabel("Mark")                              # the bottom is the MARK, not the student
plt.ylabel("How many students")                 # the height is a COUNT
plt.show()                                      # draw it

"""### `bins` — the one setting that matters

Too few and everything blurs into one block. Too many and it looks like noise. Try a few.
"""

fig, axes = plt.subplots(1, 3, figsize=(14, 3.5))   # one row, three panels, so we can compare

axes[0].hist(exam, bins=3, color="mediumpurple", edgecolor="white")    # too few - no detail
axes[0].set_title("bins=3  (too few)")                                 # label the panel

axes[1].hist(exam, bins=10, color="mediumpurple", edgecolor="white")   # about right
axes[1].set_title("bins=10  (about right)")                            # label it

axes[2].hist(exam, bins=60, color="mediumpurple", edgecolor="white")   # too many - just noise
axes[2].set_title("bins=60  (too many)")                               # label it

plt.tight_layout()                                                     # keep the titles apart
plt.show()                                                             # draw it

fig, axes = plt.subplots(1, 2, figsize=(12, 4))     # two panels side by side

axes[0].bar(["A", "B", "C", "D"], [12, 7, 15, 4], color="steelblue")   # a BAR chart: four named categories
axes[0].set_title("BAR - one bar per CATEGORY")                        # title for the left panel
axes[0].set_xlabel("Grade")                                            # the x-axis holds NAMES

axes[1].hist(exam, bins=10, color="mediumpurple", edgecolor="white")   # a HISTOGRAM: one number column
axes[1].set_title("HISTOGRAM - bars are RANGES of a number")           # title for the right panel
axes[1].set_xlabel("Mark")                                             # the x-axis holds NUMBER RANGES

plt.tight_layout()                                                     # keep them apart
plt.show()                                                             # draw it

"""---
# Section 5 — Scatter and pie
"""

plt.figure(figsize=(6, 4))                       # set the size
plt.scatter(students["maths"],                   # x = the maths marks
            students["physics"],                 # y = the physics marks
            color="darkorange",                  # dot colour
            s=70)                                # s = dot SIZE (the default is small)
plt.title("Maths vs Physics")                    # title
plt.xlabel("Maths")                              # bottom label
plt.ylabel("Physics")                            # side label
plt.grid(True, alpha=0.3)                        # faint gridlines help you read positions
plt.show()                                       # draw it

counts = students["branch"].value_counts()       # yesterday's method: how many students per branch

plt.figure(figsize=(5, 5))                       # pies look best square
plt.pie(counts.values,                           # the sizes of the slices
        labels=counts.index.tolist(),            # the label for each slice - the index holds the branch names
        autopct="%1.1f%%")                       # write the percentage on each slice, to 1 decimal place
                                                 # (with 0 decimals, 37.5 + 37.5 + 25 rounds to 38+38+25 = 101%)
plt.title("Students per branch")                 # title
plt.show()                                       # draw it

"""### ⭐ YOUR TURN 3

1. Draw a scatter of `english` against `maths`. Label everything.
2. Looking at your chart — do the two go together, or not?
"""

# YOUR TURN 3 - write your code here

plt.figure(figsize=(6, 4))                    # TODO 1: set the size
plt.scatter(students["maths"], students["english"])     # TODO 2: maths on x, english on y
plt.title("maths vs english")                                # TODO 3
plt.xlabel("Maths")                               # TODO 4
plt.ylabel("English")                               # TODO 5
plt.show()                                    # TODO 6

"""---
# Section 6 — Legends, subplots, saving
"""

completions = [8, 19, 15, 31, 30, 44]           # a second series to plot alongside the sign-ups

plt.figure(figsize=(7, 4))                                            # set the size
plt.plot(weeks, signups, marker="o", label="Sign-ups")                # label= names this line
plt.plot(weeks, completions, marker="s", label="Completions")         # marker="s" is a square
plt.title("Two series need a legend")                                 # title
plt.xlabel("Week")                                                    # bottom label
plt.ylabel("Count")                                                   # side label
plt.legend()                                                          # WITHOUT this line, no legend box appears
plt.grid(True, alpha=0.3)                                             # gridlines
plt.show()                                                            # draw it

fig, axes = plt.subplots(2, 2, figsize=(11, 7))         # a 2 x 2 grid of panels
                                                        # "fig" is the whole picture, "axes" is the grid of panels

axes[0, 0].plot(weeks, signups)                         # top-left  panel: a line
axes[0, 0].set_title("[0, 0] line")                     # note set_title, NOT plt.title, inside a panel

axes[0, 1].bar(["A", "B", "C"], [3, 7, 5])              # top-right panel: a bar chart
axes[0, 1].set_title("[0, 1] bar")                      # its title

axes[1, 0].hist(exam, bins=8)                           # bottom-left panel: a histogram
axes[1, 0].set_title("[1, 0] hist")                     # its title

axes[1, 1].scatter(students["maths"], students["physics"])   # bottom-right panel: a scatter
axes[1, 1].set_title("[1, 1] scatter")                       # its title

plt.tight_layout()                                      # stop the titles colliding - almost always needed
plt.show()                                              # draw it

plt.figure(figsize=(7, 4))                          # set the size
plt.bar(students["name"], students["total"], color="teal")   # a simple chart to save
plt.title("Total marks")                            # title
plt.xlabel("Student")                               # bottom label
plt.ylabel("Total")                                 # side label

plt.savefig("my_chart.png",                         # the filename to save as
            dpi=150,                                # sharpness - 150 is good for a report, 300 for print
            bbox_inches="tight")                    # trims the border so labels are not cut off

plt.show()                                          # show it AFTER saving - see the warning below

print("saved as my_chart.png")                      # confirm it happened

"""---
# Section 7 — Seaborn

Seaborn is not a replacement for matplotlib. It is matplotlib with the boring parts filled in:
it speaks DataFrame, it does the statistics for you, and its defaults look better.
"""

sns.set_theme()      # turn on Seaborn's styling for EVERY chart from here on, including matplotlib ones
                     # run this once near the top of a notebook and everything improves

plt.figure(figsize=(6, 4))                          # set the size
plt.bar(students["name"], students["maths"])        # a plain MATPLOTLIB chart...
plt.title("Matplotlib chart, Seaborn styling")      # ...but it picked up the new look
plt.show()                                          # draw it

from matplotlib.ticker import MaxNLocator          # a helper that forces whole-number axis ticks

plt.figure(figsize=(6, 4))                          # set the size
ax = sns.countplot(data=students, x="branch")       # data= the DataFrame, x= the COLUMN NAME as text
                                                    # notice there is no y= at all
                                                    # countplot COUNTS THE ROWS in each branch
                                                    # it hands back the axes, which we save as "ax"
ax.yaxis.set_major_locator(MaxNLocator(integer=True))   # counts are whole numbers - no "2.5 students"
plt.title("How many students per branch")           # title
plt.show()                                          # draw it

plt.figure(figsize=(6, 4))                          # set the size
sns.barplot(data=students,                          # the DataFrame
            x="branch",                             # what to group by
            y="maths",                              # what to AVERAGE - this is the difference
            errorbar=None)                          # turn off the thin black error bars (see below)
plt.title("Average maths mark per branch")          # title
plt.show()                                          # draw it

plt.figure(figsize=(7, 4))                          # set the size
sns.histplot(exam,                                  # the same 200 exam marks
             bins=10,                               # same bins setting as matplotlib
             kde=True)                              # kde=True adds a smooth curve over the bars
                                                    # it is the shape the bars are hinting at
plt.title("Exam marks, with a smooth curve")        # title
plt.xlabel("Mark")                                  # bottom label
plt.show()                                          # draw it

"""### ⭐ YOUR TURN 4

1. A `countplot` of how many students are in each **year**.
2. A `barplot` of the average **total** per **branch**, with the error bars turned off.
"""

# YOUR TURN 4 - write your code here

plt.figure(figsize=(6, 4))                                  # TODO 1: set the size
sns.countplot(data=students, x="year")                         # TODO 2: which column holds the year?
plt.title("Students per year")                                              # TODO 3
plt.xlabel("Year")                               # TODO 4
plt.ylabel("Number of Students")                               # TODO 5
plt.show()                                                  # TODO 6

plt.figure(figsize=(6, 4))                                  # TODO 5: set the size
sns.barplot(data=students, x="branch", y="total", errorbar=None)     # TODO 6: group by branch, average the total
plt.title("Average Total Marks per Branch")                                              # TODO 7
plt.xlabel("Branch")                               # TODO 4
plt.ylabel("Average Total Marks")                               # TODO 5
plt.show()                                                  # TODO 8

"""---
# Section 8 — hue, boxplot, heatmap, pairplot
"""

plt.figure(figsize=(7, 4.5))                        # set the size
sns.scatterplot(data=students,                      # the DataFrame
                x="maths",                          # x-axis column
                y="physics",                        # y-axis column
                hue="branch",                       # COLOUR the dots by branch - and build the legend automatically
                s=110)                              # dot size
plt.title("Maths vs Physics, coloured by branch")   # title
plt.show()                                          # draw it

plt.figure(figsize=(7, 4))                          # set the size
sns.boxplot(data=students, x="branch", y="total")   # one box per branch, showing the spread of totals
plt.title("Spread of totals per branch")            # title
plt.show()                                          # draw it

numbers_only = students[["maths", "physics", "english", "total"]]   # pick just the number columns
corr = numbers_only.corr().round(2)                                 # .corr( ) works out how each pair moves together
                                                                    # .round(2) trims it to 2 decimals

print(corr)                                         # look at the numbers first

plt.figure(figsize=(6, 5))                          # set the size
sns.heatmap(corr,                                   # the table of correlations
            annot=True,                             # write the number inside each square
            cmap="Blues",                           # the colour scheme - darker means higher
            vmin=-1, vmax=1)                        # fix the scale from -1 to +1 so colours mean the same thing
plt.title("Correlation between subjects")           # title
plt.show()                                          # draw it

sns.pairplot(students[["maths", "physics", "english"]])   # draws EVERY column against every other column
                                                          # with a histogram of each column down the diagonal
plt.show()                                                # draw it

"""---
# Section 9 — Choosing the right chart

Start from **the sentence you want to say out loud**, then pick the chart that says it.

---
# ★ Mini project — the class dashboard

Four charts, one figure. This is the deliverable — everything from today in one picture.
"""

fig, axes = plt.subplots(2, 2, figsize=(12, 8))     # a 2 x 2 grid, nice and big

# ---- top-left: average total per branch ----
sns.barplot(data=students, x="branch", y="total",   # group by branch, average the total
            errorbar=None,                          # no error bars - too few students per branch
            ax=axes[0, 0])                          # ax= says WHICH panel to draw into
axes[0, 0].set_title("Average total per branch")    # its title

# ---- top-right: every student's total, sorted ----
ranked = students.sort_values("total")              # sort so the bars climb
axes[0, 1].barh(ranked["name"], ranked["total"],    # horizontal bars - the names have room
                color="seagreen")                   # colour
axes[0, 1].set_title("Total marks per student")     # its title
axes[0, 1].set_xlabel("Total")                      # the number axis is along the bottom for barh

# ---- bottom-left: maths vs physics, coloured by branch ----
sns.scatterplot(data=students, x="maths", y="physics",   # the two number columns
                hue="branch",                            # colour by branch
                s=90,                                    # dot size
                ax=axes[1, 0])                           # which panel
axes[1, 0].set_title("Maths vs Physics")                 # its title

# ---- bottom-right: spread of averages per branch ----
sns.boxplot(data=students, x="branch", y="average",      # one box per branch
            ax=axes[1, 1])                               # which panel
axes[1, 1].set_title("Average by branch")                # its title

plt.tight_layout()                                  # ALWAYS the last line before show - stops collisions
plt.savefig("dashboard.png", dpi=150, bbox_inches="tight")   # save it BEFORE show( )
plt.show()                                          # draw it

print("saved as dashboard.png")                     # confirm

"""---
### ⭐ FINAL CHALLENGE

Add cells below and build these:

1. A bar chart of the **average mark per subject** — maths, physics and english as three bars.
   *(Hint: `students[["maths", "physics", "english"]].mean()` gives you a Series. Its `.index`
   holds the subject names and its `.values` hold the averages.)*
2. A histogram of all 24 marks combined — every student's maths, physics and english in one list.
   *(Hint: `students["maths"] + students["physics"]` ADDS the columns element-wise and gives you 8
   totals, which is not what you want. To stick them end to end you need plain Python lists:
   `students["maths"].tolist() + students["physics"].tolist() + students["english"].tolist()`.)*
3. A `countplot` of `branch` with `hue="year"` — how many students of each year, in each branch.
4. Save your favourite chart of the day as a PNG at `dpi=300` and download it from the folder panel.
"""

# FINAL CHALLENGE - your code here

# 1. A bar chart of the average mark per subject — maths, physics and english as three bars.
subject_averages = students[["maths", "physics", "english"]].mean()

plt.figure(figsize=(7, 4))
plt.bar(subject_averages.index, subject_averages.values, color=["indianred", "skyblue", "lightgreen"])
plt.title("Average Mark per Subject")
plt.xlabel("Subject")
plt.ylabel("Average Mark")
plt.show()

# 2. A histogram of all 24 marks combined — every student's maths, physics and english in one list.
all_marks = students["maths"].tolist() + students["physics"].tolist() + students["english"].tolist()

plt.figure(figsize=(7, 4))
sns.histplot(all_marks, bins=10, kde=True, color="steelblue")
plt.title("Distribution of All Subject Marks")
plt.xlabel("Mark")
plt.ylabel("Count")
plt.show()

# 3. A countplot of branch with hue="year" — how many students of each year, in each branch.
plt.figure(figsize=(7, 4))
sns.countplot(data=students, x="branch", hue="year", palette="viridis")
plt.title("Students per Branch, by Year")
plt.xlabel("Branch")
plt.ylabel("Number of Students")
plt.show()

# 4. Save your favourite chart of the day as a PNG at dpi=300 and download it from the folder panel.
# I will save the 'Average Mark per Subject' chart as it effectively summarizes key data.
subject_averages = students[["maths", "physics", "english"]].mean()

plt.figure(figsize=(7, 4))
plt.bar(subject_averages.index, subject_averages.values, color=["indianred", "skyblue", "lightgreen"])
plt.title("Average Mark per Subject")
plt.xlabel("Subject")
plt.ylabel("Average Mark")
plt.savefig("average_mark_per_subject.png", dpi=300, bbox_inches="tight")
plt.show()

print("Saved 'average_mark_per_subject.png' to session storage.")